services:
  mysql:
    image: mysql:8.4.7
    container_name: Car_dealer_DB
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: car_8965
      MYSQL_DATABASE: car_dealer
    volumes:
      - mysql_data:/var/lib/mysql
    
volumes: 
  mysql_data: